name: step.matrix_prepare

on:
  workflow_call:
    inputs:
      target_subproject:
        description: The subproject name of the specified Minecraft version for generating matrix entry
        type: string
        required: false
        default: ''
    outputs:
      matrix:
        description: The generated run matrix
        value: ${{ jobs.matrix_prep.outputs.matrix }}


jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Display context
        run: | 
          echo ref_name = ${{ github.ref_name }}
          echo target_subproject = ${{ github.event.inputs.target_subproject }}
          echo target_release_tag = ${{ github.event.inputs.target_release_tag }}

      - id: setmatrix
        uses: JoshuaTheMiller/conditional-build-matrix@v1.0.1
        with:
          # inputFile: '.github/workflows/matrix_includes.json' # Default input file path
          filter: '[? `${{ github.event_name }}` == `release` || `${{ github.event.inputs.target_subproject }}` == `` || `"${{ github.event.inputs.target_subproject }}"` == subproject_dir ]'

      - name: Print matrix
        run: echo ${{ steps.setmatrix.outputs.matrix }}

    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
